create table wf_controlled_loop_execution (
  execution_id bigint generated by default as identity primary key,
  deploy_id varchar(64) not null,
  process_definition_id varchar(64) not null,
  process_instance_id varchar(64) not null,
  activity_id varchar(255) not null,
  task_id varchar(64) not null,
  iteration_no int not null,
  actor_user_id varchar(64) not null,
  decision_value varchar(128) not null,
  outcome varchar(16) not null,
  create_time timestamp(3) not null,
  constraint uk_loop_task unique (task_id),
  constraint uk_loop_round unique (process_instance_id, activity_id, iteration_no)
);
