-- 多实例轮次 Mapper 与真实 Flowable 集成测试共用的 H2 表结构。
--
-- H2 只承担快速事务反馈，不冒充 MySQL 生产约束：
-- 1. members_json 使用 VARCHAR；MySQL JSON 类型、JSON_SCHEMA_VALID、成员唯一性及 Long 正整数格式
--    继续由 WfMultiInstanceRoundMapperMySqlTest 覆盖。
-- 2. MySQL 的状态组合、字段长度/正则、revision、生命周期时间 CHECK 未在此重复；这些约束仍由
--    独立 MySQL 门禁覆盖，避免两套方言逐步漂移。
-- 3. 下方 H2 生成列不是 MySQL STORED/ASCII collation 的物理等价实现，但准确复现本测试依赖的
--    业务语义：只有 ACTIVE/RETURNED 生成非 NULL 开放键，REOPENED/COMPLETED/TERMINATED 均释放键。

create table wf_multi_instance_round (
    round_id bigint generated by default as identity primary key,
    deploy_id varchar(64) not null,
    process_definition_id varchar(64) not null,
    process_instance_id varchar(64) not null,
    activity_id varchar(255) not null,
    root_execution_id varchar(64) not null,
    round_no int not null,
    mode varchar(3) not null,
    members_json varchar(4096) not null,
    revision_no int not null,
    round_status varchar(16) not null,
    return_source_task_id varchar(64),
    return_actor_user_id varchar(64),
    applicant_task_id varchar(64),
    create_time timestamp(3) not null,
    return_time timestamp(3),
    reopen_time timestamp(3),
    complete_time timestamp(3),
    terminate_time timestamp(3),
    open_process_instance_id varchar(64) generated always as
        (case when regexp_like(round_status, '^(ACTIVE|RETURNED)$')
            then process_instance_id else null end),
    open_activity_id varchar(255) generated always as
        (case when regexp_like(round_status, '^(ACTIVE|RETURNED)$')
            then activity_id else null end),
    constraint uk_wf_mi_round_instance_activity_no
        unique(process_instance_id, activity_id, round_no),
    constraint uk_wf_mi_round_root_execution unique(root_execution_id),
    constraint uk_wf_mi_round_open_activity
        unique(open_process_instance_id, open_activity_id)
);
