create table wf_process_draft (
  draft_id varchar(36) primary key,
  owner_user_id bigint not null,
  process_definition_id varchar(255) not null,
  process_definition_key varchar(255) not null,
  process_definition_version int not null,
  deployment_id varchar(64) not null,
  process_name varchar(255) not null,
  source_type varchar(32) not null,
  form_id bigint,
  form_key varchar(255) not null,
  start_node_key varchar(255) not null,
  form_name varchar(255) not null,
  node_name varchar(255) not null,
  snapshot_create_time timestamp(3) not null,
  form_snapshot clob not null,
  form_snapshot_sha256 varchar(64) not null,
  start_multi_instance_assignments clob not null,
  form_values clob not null,
  multi_instance_user_ids clob not null,
  business_key varchar(255),
  draft_status varchar(16) not null,
  revision_no bigint not null,
  submitted_process_instance_id varchar(64),
  submitted_time timestamp(3),
  deleted_time timestamp(3),
  create_time timestamp(3) not null,
  update_time timestamp(3) not null
);
