create table wf_task_sla_execution (
  sla_execution_id bigint generated by default as identity primary key,
  deployment_id varchar(64) not null,
  process_instance_id varchar(64) not null,
  process_definition_id varchar(64) not null,
  task_id varchar(64) not null,
  task_definition_key varchar(255) not null,
  assignee_user_id varchar(64),
  status varchar(16) not null,
  started_at timestamp(3) not null,
  reminder_due_at timestamp(3) not null,
  escalation_due_at timestamp(3) not null,
  reminders_sent int not null default 0,
  paused_at timestamp(3),
  paused_millis bigint not null default 0,
  revision int not null default 0,
  update_time timestamp(3) not null default current_timestamp(3),
  constraint uk_task_sla_execution_task unique(task_id)
);

create table wf_task_sla_audit (
  audit_id bigint generated by default as identity primary key,
  sla_execution_id bigint not null,
  action_type varchar(16) not null,
  action_ordinal int not null,
  actor_user_id varchar(64),
  detail varchar(500) not null,
  create_time timestamp(3) not null default current_timestamp(3),
  constraint uk_task_sla_audit_action
    unique(sla_execution_id, action_type, action_ordinal),
  constraint fk_task_sla_audit_execution foreign key(sla_execution_id)
    references wf_task_sla_execution(sla_execution_id) on delete cascade
);
